### ISSUE TITLE
Use ISO-8601 dates for release names

### ISSUE THREAD

**Issue by slel** [soehms/database_knotinfo#2]
Suggestion: use ISO 8601 format dates for release names,
i.e. YYYY-MM-DD, instead of YY.MM.DD.

**Comment by soehms** [comment]
Thanks for the suggestion, Samuel! Are you sure this will fit together with [PEP440](https://www.python.org/dev/peps/pep-0440/)? IIRC PyPI rejected such version numbers on my first attempts. But, maybe I did something else wrong!

**Comment by slel** [comment]
Then YYYYMMDD.

**Comment by slel** [comment]
Or, to follow the date-based examples in PEP440, as you did but with YYYY instead of YY.

**Comment by soehms** [comment]
> Or, to follow the date-based examples in PEP440, as you did but with YYYY instead of YY.

Yes, that should work! Probably, I was too pessimistic that people will be interested in that in the next century:)
Furthermore, I think I should truncate the padding zeros in order to avoid a divergence between GitHub and PyPI.

**Comment by soehms** [comment]
Here the [new release 2021.7.21 on PyPI](https://pypi.org/project/database-knotinfo/2021.7.21/) .

**Comment by soehms** [comment]
See comment above!
