### ISSUE TITLE
K5_2 signature change

### ISSUE THREAD

**Issue by kiwifb** [soehms/database_knotinfo#3]
I'll ask here before going to open an issue with sagemath. After the update to 2024.5.1 in sagemath it seems the tested signature has changed
```
File "/usr/lib/python3.12/site-packages/sage/knots/knotinfo.py", line 898, in sage.knots.knotinfo.KnotInfoBase.signature
Failed example:
    KnotInfo.K5_2.signature()       # optional - database_knotinfo
Expected:
    1
Got:
    -2
```
Trying with 2024.8.1 gives the same result (-2). I find it strange that the property of a particular knot would change like that. Was the doctest always wrong, or was there something wrong in the database or is something fishy going on?

**Comment by soehms** [comment]
> Was the doctest always wrong, or was there something wrong in the database or is something fishy going on?

No! The doctest didn' work before https://github.com/sagemath/sage/pull/38118 which has been merged currently. In that PR the doctest has been made working but with a wrong result. This will be fixed with https://github.com/sagemath/sage/pull/38254.

**Comment by kiwifb** [comment]
Was always wrong. I feel better about that now. Good to see there is work to fix it.
